markdown:
  preset: "default"
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
  plugins:
    - name: "@renbaoshuo/markdown-it-katex"
      options:
        skipDelimitersCheck: true
  options:
    katex:
      throwOnError: true
      output: "html"
      strict: true
      breakOnSingleLine: true

theme: next