title: doge-liang-notebook
subtitle: doge-liang's notebook
description: 什么都记的笔记本
keywords: null
author: doge-liang
language: en
timezone: asia/shanghai
url: 'https://doge-liang.github.io/doge-liang-notebook'
root: /doge-liang-notebook/
permalink: 'post/:category/:post_title/'
permalink_defaults: null
pretty_urls:
  trailing_index: false
  trailing_html: false
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: categories
tag_map: tags
meta_generator: true
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
updated_option: mtime
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
theme: next
deploy:
  repository: 'https://github.com/doge-liang/doge-liang-notebook.git'
  type: git
  branch: master
math:
  engine: katex
  katex:
    css: 'https://cdn.bootcss.com/KaTeX/0.11.1/katex.min.css'
    js: 'https://cdn.bootcss.com/KaTeX/0.11.1/katex.min.js'
    config:
      throwOnError: false
      errorColor: '#cc0000'
    enable: false
    copy_tex: false
  every_page: false
  mathjax:
    enable: false
    tags: none
mermaid:
  enable: false
  version: 7.1.2
  options:
    startOnload: true  // default true
  theme:
    light: default
    dark: dark
cache:
  enable: true
minify: false
custom_file_path: null
scheme: Muse
darkmode: true
favicon:
  small: /images/favicon-16x16-next.png
  medium: /images/favicon-32x32-next.png
  apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo.svg
custom_logo: null
creative_commons:
  license: by-nc-sa
  size: small
  sidebar: false
  post: false
  language: null
open_graph:
  enable: true
  options: null
menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  schedule: /schedule/ || fa fa-calendar
  sitemap: /sitemap.xml || fa fa-sitemap
  commonweal: /404/ || fa fa-heartbeat
menu_settings:
  icons: true
  badges: false
sidebar:
  position: left
  display: post
  padding: 18
  offset: 12
avatar:
  url: null
  rounded: false
  rotated: false
site_state: true
social: null
social_icons:
  enable: true
  icons_only: false
  transition: false
links_settings:
  icon: fa fa-globe
  title: Links
  layout: block
links: null
toc:
  enable: true
  number: true
  wrap: false
  expand_all: false
  max_depth: 6
language_switcher: false
footer:
  icon:
    name: fa fa-heart
    animated: false
    color: '#ff0000'
  copyright: null
  powered: true
  beian:
    enable: false
    icp: null
    gongan_id: null
    gongan_num: null
    gongan_icon_url: null
excerpt_description: true
read_more_btn: true
post_meta:
  item_text: true
  created_at: true
  updated_at:
    enable: true
    another_day: true
  categories: true
symbols_count_time:
  separated_meta: true
  item_text_total: false
tag_icon: false
reward_settings:
  enable: false
  animation: false
reward: null
follow_me: null
related_posts:
  enable: false
  title: null
  display_in_home: false
post_edit:
  enable: false
  url: 'https://github.com/user-name/repo-name/tree/branch-name/subdirectory-name/'
post_navigation: left
tagcloud:
  min: 12
  max: 30
  amount: 200
  orderby: name
  order: 1
calendar:
  calendar_id: <required>
  api_key: <required>
  orderBy: startTime
  showLocation: false
  offsetMax: 72
  offsetMin: 4
  showDeleted: false
  singleEvents: true
  maxResults: 250
preconnect: false
text_align:
  desktop: justify
  mobile: justify
mobile_layout_economy: false
theme_color:
  light: '#222'
  dark: '#222'
body_scrollbar:
  overlay: false
  stable: false
codeblock:
  theme:
    light: default
    dark: stackoverflow-dark
  prism:
    light: prism
    dark: prism-dark
  copy_button:
    enable: false
    style: null
back2top:
  enable: true
  sidebar: false
  scrollpercent: false
reading_progress:
  enable: false
  start_at: left
  position: top
  reversed: false
  color: '#37c6c0'
  height: 3px
bookmark:
  enable: false
  color: '#222'
  save: auto
github_banner:
  enable: false
  permalink: 'https://github.com/yourname'
  title: Follow me on GitHub
font:
  enable: false
  host: null
  global:
    external: true
    family: Lato
    size: null
  title:
    external: true
    family: null
    size: null
  headings:
    external: true
    family: null
    size: null
  posts:
    external: true
    family: null
  codes:
    external: true
    family: null
index_with_subtitle: false
exturl: false
exturl_icon: true
google_site_verification: null
bing_site_verification: null
yandex_site_verification: null
baidu_site_verification: null
pjax: false
fancybox: false
mediumzoom: false
lazyload: false
pangu: false
quicklink:
  enable: false
  home: false
  archive: false
  delay: true
  timeout: 3000
  priority: true
comments:
  style: tabs
  active: null
  storage: true
  lazyload: false
  nav: null
disqus:
  enable: false
  shortname: null
  count: true
disqusjs:
  enable: false
  api: null
  apikey: null
  shortname: null
changyan:
  enable: false
  appid: null
  appkey: null
livere_uid: null
gitalk:
  enable: false
  github_id: null
  repo: null
  client_id: null
  client_secret: null
  admin_user: null
  distraction_free_mode: true
  proxy: >-
    https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token
  language: null
utterances:
  enable: false
  repo: user-name/repo-name
  issue_term: pathname
  theme: github-light
isso: null
rating:
  enable: false
  id: null
  color: '#fc6423'
add_this_id: null
google_analytics:
  tracking_id: null
  only_pageview: false
baidu_analytics: null
growingio_analytics: null
cloudflare_analytics: null
clarity_analytics: null
leancloud_visitors:
  enable: false
  app_id: null
  app_key: null
  server_url: null
  security: true
firestore:
  enable: false
  collection: articles
  apiKey: null
  projectId: null
busuanzi_count:
  enable: false
  total_visitors: true
  total_visitors_icon: fa fa-user
  total_views: true
  total_views_icon: fa fa-eye
  post_views: true
  post_views_icon: far fa-eye
algolia_search:
  enable: false
  hits:
    per_page: 10
local_search:
  enable: false
  trigger: auto
  top_n_per_article: 1
  unescape: false
  preload: false
chat:
  enable: false
  icon: fa fa-comment
  text: Chat
chatra:
  enable: false
  async: true
  id: null
tidio:
  enable: false
  key: null
gitter:
  enable: false
  room: null
note:
  style: simple
  icons: false
  light_bg_offset: 0
tabs:
  sticky: false
  transition:
    tabs: false
    labels: true
pdf:
  enable: false
  height: 500px
motion:
  enable: true
  async: false
  transition:
    post_block: fadeIn
    post_header: fadeInDown
    post_body: fadeInDown
    coll_header: fadeInLeft
    sidebar: fadeInUp
pace:
  enable: false
  color: blue
  theme: minimal
canvas_ribbon:
  enable: false
  size: 300
  alpha: 0.6
  zIndex: -1
vendors:
  internal: local
  plugins: cdnjs
  custom_cdn_url: null
css: css
js: js
images: images
